browser = chrome
url= http://orangehrm.qedgetech.com/symfony/web/index.php/auth
employid=//input[@id='empsearch_id']
employid_search=//input[@id='searchBtn']
admin_username=//input[@id='searchSystemUser_userName']
admin_search=//input[@id='searchBtn']
